package com.sun.hibernate.Dao;
// Generated Jan 10, 2010 11:27:38 AM by Hibernate Tools 3.2.1.GA


/**
 * UserDetails generated by hbm2java
 */
public class RoleDAO extends BaseHibernateDAO{    
    
}
