/* $Header: /home/common/cvsarea/ibase/dia/src/beans/CancelDialog.java,v 1.6.6.1 2006/02/22 20:05:50 nancy Exp $ */

/*
 * CancelDialog.java
 *
 * Created on May 8, 2003, 6:01 PM
 */
package beans;

import javax.swing.JOptionPane;

/**
 * Called from <code>ui.SplitPaneViewer</code>, this dialog is used
 * to stop the image run started by <code>vBeginImageRunButton</code>.
 * 
 * @author  Nancy
 */
public class CancelDialog extends javax.swing.JDialog {

    /**
     * Creates new form CancelDialog.
     * @param parent the component to use in positioning this dialog
     * @param modal true if this dialog should be modal; false
     * for one that allows other windows to be active at the same time
     */
    public CancelDialog(java.awt.Component parent, boolean modal) {
        super(JOptionPane.getFrameForComponent(parent));
        setModal(true);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        stopButton = new javax.swing.JButton();

        setTitle("Stop Scroll");
        setName("Stop Scroll");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(50, 50));
        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stopsign.gif")));
        stopButton.setToolTipText("Stop Image Scroll");
        stopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButtonMouseClicked(evt);
            }
        });

        jPanel1.add(stopButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void stopButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButtonMouseClicked
        setVisible(false);

        dispose();
    }//GEN-LAST:event_stopButtonMouseClicked

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new CancelDialog(new javax.swing.JFrame(), true).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
