package com.sun.hibernate.domain;
// Generated Feb 2, 2010 11:35:20 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
/**
 * Transaction generated by hbm2java
 */
public class Transaction extends  Domain {


     private Integer transactionId;
     private Date transactionDate;
     private BigDecimal transactionAmt;
     private BigDecimal summaryAmt;
     private String currencyCode;
     private String invoiceNumber;
     private String checkNumber;
     private BigDecimal balance;
     private String status;
     private String userType;
     private Date dueDate;
     private String bankName;
     private String bankAccountNumber;
     private Date checkDate;
     private String referenceNumber;
     private String paymentMethod;
     private Date createdOn;
     private String createdBy;
     private Date updatedOn;
     private String updatedBy;
     private Date closedDate;
     private User user;
     // temp for display
     private Double providerAmount;
     private String providerCompanyName;

    public Transaction() {
    }

    public Transaction(Date transactionDate, BigDecimal transactionAmt, String currencyCode, String invoiceNumber, String checkNumber, BigDecimal balance, String status, Date dueDate, String bankName, String bankAccountNumber, Date checkDate, String referenceNumber, String paymentMethod, Date createdOn, String createdBy, Date updatedOn, String updatedBy, Date closedDate) {
       this.transactionDate = transactionDate;
       this.transactionAmt = transactionAmt;
       this.currencyCode = currencyCode;
       this.invoiceNumber = invoiceNumber;
       this.checkNumber = checkNumber;
       this.balance = balance;
       this.status = status;
       this.dueDate = dueDate;
       this.bankName = bankName;
       this.bankAccountNumber = bankAccountNumber;
       this.checkDate = checkDate;
       this.referenceNumber = referenceNumber;
       this.paymentMethod = paymentMethod;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.updatedOn = updatedOn;
       this.updatedBy = updatedBy;
       this.closedDate = closedDate;
    }
   
    public Integer getTransactionId() {
        return this.transactionId;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public BigDecimal getTransactionAmt() {
        return this.transactionAmt;
    }
    
    public void setTransactionAmt(BigDecimal transactionAmt) {
        this.transactionAmt = transactionAmt;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public String getInvoiceNumber() {
        return this.invoiceNumber;
    }
    
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
    public String getCheckNumber() {
        return this.checkNumber;
    }
    
    public void setCheckNumber(String checkNumber) {
        this.checkNumber = checkNumber;
    }
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }
    public String getBankAccountNumber() {
        return this.bankAccountNumber;
    }
    
    public void setBankAccountNumber(String bankAccountNumber) {
        this.bankAccountNumber = bankAccountNumber;
    }
    public Date getCheckDate() {
        return this.checkDate;
    }
    
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }
    public String getReferenceNumber() {
        return this.referenceNumber;
    }
    
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    public Double getProviderAmount() {
        return providerAmount;
    }

    public void setProviderAmount(Double providerAmount) {
        this.providerAmount = providerAmount;
    }
    
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getClosedDate() {
        return this.closedDate;
    }
    
    public void setClosedDate(Date closedDate) {
        this.closedDate = closedDate;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public BigDecimal getSummaryAmt() {
        return summaryAmt;
    }

    public void setSummaryAmt(BigDecimal summaryAmt) {
        this.summaryAmt = summaryAmt;
    }

    public String getProviderCompanyName() {
        return providerCompanyName;
    }

    public void setProviderCompanyName(String providerCompanyName) {
        this.providerCompanyName = providerCompanyName;
    }

    
}


