/* $Header: /home/common/cvsarea/ibase/dia/src/ui/Attic/CustomerPricePage.java,v 1.1.2.5 2006/03/30 12:28:55 nancy Exp $ */
/*
 * CustomerPricePage.java
 *
 * Created on July 26, 2005, 10:15 AM
 */
package ui;

import beans.AddEditCustomerprice;
import beans.ToolTipText;
import common.Log;
import common.CustomerpriceData;
import model.ManagedComboModel;
import model.ManagedTableModel;
import model.ManagedTableSorter;
import model.QueryComboModel;
import model.SQLManagedTableModel;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Point;

import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;


/**
 * On the AdminFrame, this is the Receivables screen that shows prices
 * received for each project by volume and level.  Prices are for Unitize
 * page and document and Coding page and document.  The first line of the
 * table is the volume default; in other words, if a volume is not specifically
 * priced, the volume default will be used.  Specific volume prices that
 * do not match the first line show in bold green.  All other prices are in
 * black.
 * <p>
 * The user may select a line and click Edit (or double click a line) to change
 * the prices for any line via <code>beans.AddEditCustomprice</code>.
 * @author  Nancy McCall
 * @see beans.AddEditCustomerprice
 */
public final class CustomerPricePage extends ui.AbstractPage
{

   private final String GET_ALL_VOLUMES = "Import Export.get all volumes";
   private QueryComboModel volumeModel = null;
   private ManagedTableSorter pModel = null;
   private ManagedComboModel projectModel = null;
   private ManagedComboModel projectModelFilter = null;
   private int projectId = 0;
   private int volumeId = 0;
   private int customerpriceId = 0;
   private String projectName = "";
   private String[] tableHeadings;

   /** Creates new form CustomerPricePage */
   public CustomerPricePage(AdminFrame frame)
   {
      super(frame);
      initComponents();

      // keep the customerpriceTable model headings for use in loading the table data
      tableHeadings = new String[customerpriceTable.getColumnModel().getColumnCount()];
      TableModel model = customerpriceTable.getModel();
      for (int i = 0; i < tableHeadings.length; i++) {
         tableHeadings[i] = model.getColumnName(i);
      }
   }

   /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        xrefFormatGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        projectCombo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        fieldsScrollPane = new javax.swing.JScrollPane();
        customerpriceTable = new CustomerpriceTableClass();
        jPanel1 = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();

        fileMenu.setMnemonic('F');
        fileMenu.setText("File");
        exitMenuItem.setMnemonic('E');
        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Exit program.");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 24));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Receivables");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(titleLabel, gridBagConstraints);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14));
        jLabel1.setText("Select Project: ");
        jPanel10.add(jLabel1, new java.awt.GridBagConstraints());

        projectCombo.setPreferredSize(new java.awt.Dimension(175, 25));
        projectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectComboActionPerformed(evt);
            }
        });

        jPanel13.add(projectCombo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel10.add(jPanel13, gridBagConstraints);

        jPanel6.add(jPanel10, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jPanel6, gridBagConstraints);

        fieldsScrollPane.setPreferredSize(new java.awt.Dimension(653, 403));
        customerpriceTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        customerpriceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Volume", "Lvl", "U. Page", "U. Doc", "C. Page", "C. Doc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerpriceTable.setFocusable(false);
        customerpriceTable.setIntercellSpacing(new java.awt.Dimension(2, 1));
        customerpriceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerpriceTableMouseClicked(evt);
            }
        });

        fieldsScrollPane.setViewportView(customerpriceTable);

        jPanel2.add(fieldsScrollPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        add(jPanel2, gridBagConstraints);

        editButton.setFont(new java.awt.Font("Dialog", 0, 12));
        editButton.setText("Edit");
        editButton.setToolTipText("");
        editButton.setFocusable(false);
        editButton.setEnabled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jPanel1.add(editButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        add(jPanel1, gridBagConstraints);

    }//GEN-END:initComponents

    private void customerpriceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerpriceTableMouseClicked
       try {
          if (evt.getClickCount() > 1 &&
                  customerpriceTable.getSelectedRow() > -1) { // 2007-06-14: changed here
                // double-click on a row
             editButton.doClick();
          }
          if (customerpriceTable.getSelectedRow() > -1) {
             editButton.setEnabled(true);
          }
          else {
             editButton.setEnabled(false);
          }
       } catch (Throwable th) {
          Log.quit(th);
       }
    }//GEN-LAST:event_customerpriceTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
       try {
          assert projectId > 0;

          CustomerpriceData cp = new CustomerpriceData();

          int i = customerpriceTable.getSelectedRow();
          ManagedTableSorter model = (ManagedTableSorter) customerpriceTable.getModel();

          int level = 0;
          String volume = (String) model.getValueAt(i, 6);
          if (volume != null & !volume.equals("")) {
             cp.volume_id = Integer.parseInt(volume);
          }
          String levelString = (String) model.getValueAt(i, 1);
          if (levelString != null & !levelString.equals("")) {
             cp.field_level = Integer.parseInt(levelString);
          }

          cp.customerprice_id = model.getRowId(i);
          cp.project_id = projectId;
          cp.unitize_page_price = (String) model.getValueAt(i, 2);
          cp.unitize_doc_price = (String) model.getValueAt(i, 3);
          cp.coding_page_price = (String) model.getValueAt(i, 4);
          cp.coding_doc_price = (String) model.getValueAt(i, 5);

          AddEditCustomerprice priceDialog;
          priceDialog = new AddEditCustomerprice((java.awt.Component) this, projectName, (String) model.getValueAt(i, 0) // volume_name
                  , cp);
          priceDialog.setModal(true);
          priceDialog.show();
          ((ManagedTableSorter) customerpriceTable.getModel()).fireTableDataChanged();
          if (customerpriceTable.getSelectedRow() == -1) {
             editButton.setEnabled(false);
          }
       } catch (Throwable th) {
          Log.quit(th);
       }
    }//GEN-LAST:event_editButtonActionPerformed

    private void projectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectComboActionPerformed
       try {
          int projectIndex = projectCombo.getSelectedIndex();
          projectId = (projectIndex >= 0
                  ? ((ManagedComboModel) projectCombo.getModel()).getIdAt(projectIndex)
                  : 0);
          if (projectId > 0) {
             projectName = (String) projectCombo.getSelectedItem();

             // The painted column names are retained
                // Sort on column 11, sequence
             SQLManagedTableModel unsortedModel = SQLManagedTableModel.makeInstance("CustomerPricePage.customerpriceTable",
                     customerpriceTable.getModel(),
                     projectId);
             unsortedModel.setColumnClass(7, Integer.class);  // sequence
             ManagedTableModel model = new ManagedTableSorter(new int[]{7, 1}, unsortedModel);
             customerpriceTable.setModel(model);
             model.register();

             //addButton.setEnabled(true);
             editButton.setEnabled(false);
          //deleteButton.setEnabled(false);
          }
          else {
             projectName = "";
             //addButton.setEnabled(false);
             editButton.setEnabled(false);
          //deleteButton.setEnabled(false);
          }

          customerpriceTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          // set the table row colors and justification
          TableColumn column = null;
          for (int i = 0; i < customerpriceTable.getColumnCount(); i++) {
             column = customerpriceTable.getColumnModel().getColumn(i);
             column.setCellRenderer(formatCell);
          }
          column = customerpriceTable.getColumnModel().getColumn(0);
          column.setPreferredWidth(150);
          column = customerpriceTable.getColumnModel().getColumn(1);
          column.setPreferredWidth(35);

          customerpriceTable.getModel().addTableModelListener(new RepaintCells());
       } catch (Throwable th) {
          Log.quit(th);
       }
    }//GEN-LAST:event_projectComboActionPerformed

   /**
     * Check that it's OK to exit the current page.  Subclasses must override this to provide a
     * page-dependent check.
     * @return true if it's OK to exit.  If field cancels save/no-save/cancel dialog,
     *         false is returned.
     */
   protected boolean exitPageCheck()
   {
      // TBD
      return true;
   }

   /** Get the menu bar for the current page.  Subclasses must override this to provide a
     * page-dependent menu bar.
     */
   protected javax.swing.JMenuBar getPageJMenuBar()
   {
      return menuBar;
   }

   /**
     * Perform page initialization.  Subclasses must override this to provide any
     * required page-dependent initialization.
     * 
     * Create a filtered and unfiltered model for project, volume, batch and batchEnd combos.
     */
   protected void tabSelected()
   {
      Log.print("CustomerPricePage tabSelected");

      // project model
      if (pModel == null) {
         pModel = new ManagedTableSorter(0, SQLManagedTableModel.makeInstance("CustomerPricePage.projectCombo"));
         projectModel = new ManagedComboModel(pModel);
         pModel.register();
         projectCombo.setModel(projectModel);
      }
   }

   private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
       try {
          exitForm();
       } catch (Throwable th) {
          Log.quit(th);
       }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerpriceTable;
    private javax.swing.JButton editButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JScrollPane fieldsScrollPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JComboBox projectCombo;
    private javax.swing.JLabel titleLabel;
    private javax.swing.ButtonGroup xrefFormatGroup;
    // End of variables declaration//GEN-END:variables

   private class CustomerpriceTableClass extends JTable
   {

      public String getToolTipText(MouseEvent event)
      {
         return ToolTipText.getToolTipText(event, customerpriceTable);
      }

      public Point getToolTipLocation(MouseEvent event)
      {
         return ToolTipText.getToolTipLocation(event, customerpriceTable);
      }

   }

   TableCellRenderer formatCell = new DefaultTableCellRenderer()
           {
              /**
         *
         * Returns the default table cell renderer.
         *
         * @param table  the <code>JTable</code>
         * @param value  the value to assign to the cell at
         *			<code>[row, column]</code>
         * @param isSelected true if cell is selected
         * @param hasFocus true if cell has focus
         * @param row  the row of the cell to render
         * @param column the column of the cell to render
         * @return the default table cell renderer
         */

              public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
              {
                 Component renderer = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                 //Log.print("(CustomerPricePage.renderer) enter");

                 if (column > 0) {
                    setHorizontalAlignment(JLabel.RIGHT);
                 }
                 else {
                    setHorizontalAlignment(JLabel.LEFT);
                 }
                 if (isSelected) {
                    // leave default background
                    return this;
                 }

                 if (row % 2 == 1) {
                    renderer.setBackground(new Color(234, 234, 234));
                    renderer.setForeground(Color.black);
                 }
                 else {
                    renderer.setBackground(Color.white);
                    renderer.setForeground(Color.black);
                 }
                 ManagedTableModel model = (ManagedTableModel) customerpriceTable.getModel();
                 int i = model.getRowCount() + 1;
                 int thisLevel = Integer.parseInt((String) model.getValueAt(row, 1));
                 if (column > 1 && !((String) model.getValueAt(row, 6)).equals("0")) { // volume_id <> 0
                // price
                    for (i = 0; i < model.getRowCount(); i++) {
                       if (thisLevel == Integer.parseInt((String) model.getValueAt(i, 1)) && ((String) model.getValueAt(i, 6)).equals("0")) {
                          // the default row for this level
                          if (!((String) value).equals((String) model.getValueAt(i, column))) {
                             // reverse colors to flag a non-matching value
                            //Color color = renderer.getBackground();
                            //renderer.setBackground(renderer.getForeground());
                            //Log.print("(CustomerPricePage.repaint) setForeground green");
                             renderer.setForeground(Color.green.darker());
                             Font font = renderer.getFont();
                             renderer.setFont(new Font(font.getFontName(), Font.BOLD, font.getSize()));
                          }
                          i = model.getRowCount() + 1;
                          break;
                       }
                       if (0 < Integer.parseInt((String) model.getValueAt(i, 6))) {
                          // beyond default volumes
                          break;
                       }
                    }
                 }
                 if (i < model.getRowCount()) {
                    // didn't find a default for this level, so make it darker gray
                //Log.print("(CustomerPricePage.repaint) setBackground lightGray");
                    renderer.setBackground(Color.lightGray);
                 }
                 return this;
              }

           };

   /**
     * This listener detects changes to the default volume rows of the customerpriceTable
     * and initiates a fireTableRowsUpdated on the rows following the defaults to
     * cause the renderer to repaint the prices with the appropriate colors.
     * 
     * NOTE:  This logic assumes the model is sorted by volume.sequence (column 7) first!
     */
   private class RepaintCells implements TableModelListener
   {
      /**
         * This fine grain notification tells listeners the exact range
         * of cells, rows, or columns that changed.
         */

      public void tableChanged(TableModelEvent e)
      {
         ManagedTableSorter model = (ManagedTableSorter) e.getSource();
         if (e.getFirstRow() >= model.getRowCount()) {
            return;
         }
         int i;
         if (((String) model.getValueAt(e.getFirstRow(), 6)).equals("0")) {
            // default volume
                // get beyond default volumes
            for (i = e.getFirstRow() + 1; i < model.getRowCount(); i++) {
               if (!((String) model.getValueAt(i, 6)).equals("0")) {
                  break;
               }
            }
            model.fireTableRowsUpdated(i, model.getRowCount() - 1);
         }
      }

   }

}
