/*
 * DTYGModViewEdit.java
 *
 * Created on June 6, 2008, 10:20 AM
 */
package ui;

import client.TaskSaveDTYGModData;
import common.DTYGFieldsData;
import client.ClientTask;


import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.XeroxTableModel;

/**
 *
 * @author  sunil
 */
public class DTYGModViewEdit extends javax.swing.JFrame {

    private DTYGMod parent;
    private XeroxTableModel xeroxTableModel;
    private List<DTYGFieldsData> updatedDTYGList;
    private List values = null;

    /** Creates new form DTYGModViewEdit */
    public DTYGModViewEdit() {
        initComponents();
    }

    /**
     * To instantiate an object 
     * @param parent -- parent form
     * @param dtygDataList -- a complete list of date to be displyed.
     * @param values
     */
    public DTYGModViewEdit(DTYGMod parent, ArrayList<DTYGFieldsData> dtygDataList, List values) {
        initComponents();
        this.parent = parent;
        this.values = values;
        parent.xeroxProgressBar.setValue(0);
        parent.footerLabel.setText("IDLE");
        fillDataToTable(dtygDataList);
    }

    /**
     * Save the records into the database.
     * write the data to the new excel sheet.
     * @return
     */
    private boolean save() {
        ClientTask task;
        updatedDTYGList = new ArrayList<DTYGFieldsData>();
        DTYGFieldsData dtyg = null;
        Object data[][] = xeroxTableModel.getData();
        for (Object row[] : data) {
            try {
                // if the first row is null then iterate to the next row (if any)
                if (row[0] == null || row[0].toString().trim().equals("")) {
                    continue;
                }
                dtyg = (DTYGFieldsData) row[9];
                dtyg.begImage = (row[1] != null ? row[1].toString() : "");
                dtyg.endImage = (row[2] != null ? row[2].toString() : "");
                dtyg.specVersion = (row[3] != null ? row[3].toString() : "");
                dtyg.dateSubmitted = (row[4] != null ? row[4].toString() : "");
                dtyg.spiQuestions = (row[5] != null ? row[5].toString() : "");
                dtyg.field = (row[6] != null ? row[6].toString() : "");
                dtyg.xeroxResponses = (row[7] != null ? row[7].toString() : "");
                dtyg.lookup = (row[8] != null ? row[8].toString() : "");
                updatedDTYGList.add(dtyg);
                task = new TaskSaveDTYGModData(dtyg);
                task.enqueue(this);
            //break;
            } catch (ArrayIndexOutOfBoundsException e) {
                e.printStackTrace();
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, e);
            }
        }

        // write the updated DTYG records to the new excel sheet by calling the method
        // <code> writeModfiedXerox </code> written in class <code> DTYGMod </code>
        ((DTYGMod) parent).writeModfiedXerox();

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, "Record has been saved successfully");
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
private void initComponents() {
java.awt.GridBagConstraints gridBagConstraints;

jLabel1 = new javax.swing.JLabel();
jButton1 = new javax.swing.JButton();
jLayeredPane1 = new javax.swing.JLayeredPane();
viewEditPanel = new javax.swing.JPanel();
jScrollPane1 = new javax.swing.JScrollPane();
viewEditTable = new javax.swing.JTable();
jMenuBar1 = new javax.swing.JMenuBar();
saveMenu = new javax.swing.JMenu();
exitMenu = new javax.swing.JMenu();

jLabel1.setText("jLabel1");

jButton1.setText("jButton1");

setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
setBackground(new java.awt.Color(217, 246, 214));
setFocusCycleRoot(false);
addWindowListener(new java.awt.event.WindowAdapter() {
public void windowClosing(java.awt.event.WindowEvent evt) {
formWindowClosing(evt);
}
});
getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

viewEditPanel.setBackground(new java.awt.Color(217, 246, 214));
viewEditPanel.setLayout(new java.awt.GridBagLayout());

viewEditTable.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		
	},
	new String [] {
		"BatchID", "BegImage", "EndImage", "Spec Version", "Date Submitted", "SPI Questions", "Field", "Xerox Responses", "Look Up"
	}
) {
	boolean[] canEdit = new boolean [] {
		false, true, false, false, true, true, false, false, true
	};

	public boolean isCellEditable(int rowIndex, int columnIndex) {
		return canEdit [columnIndex];
	}
});
viewEditTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
viewEditTable.setPreferredSize(new java.awt.Dimension(1000, 300));
jScrollPane1.setViewportView(viewEditTable);

gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 0;
gridBagConstraints.gridy = 0;
gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
gridBagConstraints.ipadx = 200;
gridBagConstraints.ipady = -100;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.weightx = 1.0;
gridBagConstraints.weighty = 1.0;
gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
viewEditPanel.add(jScrollPane1, gridBagConstraints);

getContentPane().add(viewEditPanel);

saveMenu.setText("Save");
saveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.gif"))); // NOI18N
saveMenu.addMenuListener(new javax.swing.event.MenuListener() {
public void menuCanceled(javax.swing.event.MenuEvent evt) {
}
public void menuDeselected(javax.swing.event.MenuEvent evt) {
}
public void menuSelected(javax.swing.event.MenuEvent evt) {
saveMenuMenuSelected(evt);
}
});
jMenuBar1.add(saveMenu);

exitMenu.setText("Exit");
exitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.gif"))); // NOI18N
exitMenu.addMenuListener(new javax.swing.event.MenuListener() {
public void menuCanceled(javax.swing.event.MenuEvent evt) {
}
public void menuDeselected(javax.swing.event.MenuEvent evt) {
}
public void menuSelected(javax.swing.event.MenuEvent evt) {
exitMenuMenuSelected(evt);
}
});
jMenuBar1.add(exitMenu);

setJMenuBar(jMenuBar1);

pack();
}// </editor-fold>//GEN-END:initComponents

private void exitMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_exitMenuMenuSelected
    this.dispose();
    parent.setVisible(true);
}//GEN-LAST:event_exitMenuMenuSelected

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.dispose();
    parent.setVisible(true);
}//GEN-LAST:event_formWindowClosing

private void saveMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_saveMenuMenuSelected
    save();
}//GEN-LAST:event_saveMenuMenuSelected

    /**
     * Display the DTYG data to the table
     * Table contains 9 columns.
     * @param dtygDataList -- complete DTYG records
     */
    public void fillDataToTable(ArrayList<DTYGFieldsData> dtygDataList) {

        String headings[] = {"BatchID", "BegImage", "EndImage", "Spec Version", "Date Submitted", "SPI Questions", "Field", "Xerox Responses", "Look Up"};
        Object object[][] = new Object[dtygDataList.size()][headings.length + 1];
        DTYGFieldsData dfd;
        for (int i = 0; i < dtygDataList.size(); i++) {
            dfd = dtygDataList.get(i);
            //if(null != dfd.xeroxResponses && dfd.xeroxResponses.trim().equals("")){
            if (dfd.batchID == null || dfd.toString().trim().equals("")) {
                i--;
                continue;
            }
            object[i][0] = dfd.batchID;
            object[i][1] = dfd.begImage;
            object[i][2] = dfd.endImage;
            object[i][3] = dfd.specVersion;
            object[i][4] = dfd.dateSubmitted;
            object[i][5] = dfd.spiQuestions;
            object[i][6] = dfd.field;
            object[i][7] = dfd.xeroxResponses;
            object[i][8] = "";
            object[i][9] = dfd;
        //}
        }
        xeroxTableModel = new XeroxTableModel(object, headings);
        viewEditTable.setModel(xeroxTableModel);
        //String aaa= dfd.xeroxResponses;
        if (values != null && values.size() >= 0) {
            JComboBox combo = new JComboBox(values.toArray());
            viewEditTable.getColumnModel().getColumn(8).setCellEditor(new DefaultCellEditor(combo));
            for (int j = 0; j < dtygDataList.size(); j++) {
                dfd = dtygDataList.get(j);
                String xerox_response = dfd.xeroxResponses;
                xerox_response = xerox_response.toLowerCase();
                String lookupvalue_list = "";
                if (null != xerox_response && !xerox_response.trim().equals("")) {
                    for (int i = 0; i < values.size(); i++) {
                        String match_string = (String) values.get(i);
                        String ddd = match_string.substring(0, 1);
                        // String sss =  ddd.toLowerCase();                     
                        if (xerox_response.matches((String) values.get(i)) || xerox_response.startsWith(ddd)) {
                            lookupvalue_list = (String) values.get(i);
                            viewEditTable.getModel().setValueAt(lookupvalue_list, j, 8);
                            break;
                        } else {
                            viewEditTable.getModel().setValueAt("report", j, 8);
                        }

                    }
                }
            }
        }
    }
// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JMenu exitMenu;
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLayeredPane jLayeredPane1;
private javax.swing.JMenuBar jMenuBar1;
private javax.swing.JScrollPane jScrollPane1;
private javax.swing.JMenu saveMenu;
private javax.swing.JPanel viewEditPanel;
private javax.swing.JTable viewEditTable;
// End of variables declaration//GEN-END:variables
}
