/*
 * FieldFormat.java
 *
 * Created on 29 September, 2008, 3:31 PM
 */
package ui;

import valueobjects.FieldFormatData;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

/**
 * Output Format window used for Formatting the Field.
 * @author  sunil
 */
public class FieldFormat extends javax.swing.JFrame {

    private Component parent;
    private StringBuilder buffer;
    private FieldFormatData selectedFieldFormatData;

    /** Creates new form FieldFormat */
    public FieldFormat(Component parent, int selectedRow) {
        initComponents();
        buffer = new StringBuilder();
        //formatTextArea.setText("<sfkldjk><lf><jsdkljfl> <klfj> <skldjfl> <kjsdkljflk>");
        formatTextArea.setSelectedTextColor(Color.green);
        formatTextArea.setSelectionColor(Color.GRAY);
        formatTextArea.setEditable(false);
        formatTextArea.setLineWrap(true);
        this.parent = parent;
        setLocationRelativeTo(parent);

        deliminatorComboBox.setModel(new javax.swing.DefaultComboBoxModel(FieldFormatData.getDeliminators()));
        List<FieldFormatData> formatFieldList = ((OutputFormat) parent).getFieldList();
        selectedFieldFormatData = formatFieldList.get(selectedRow);

        ArrayList<String> fieldList = new ArrayList<String>();
        fieldList.add("");
        for (int i = 0; i < formatFieldList.size(); i++) {
            if (formatFieldList.get(i).getType().equals(FieldFormatData.PROJECT_FIELD)) {
                fieldList.add(formatFieldList.get(i).getName());
            }
        }

        fieldComboBox.setModel(new javax.swing.DefaultComboBoxModel(fieldList.toArray()));
        formatTextArea.setText(selectedFieldFormatData.getFormat());
        fieldNameLabel.setText(selectedFieldFormatData.getName());
        ((OutputFormat) parent).setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
private void initComponents() {//GEN-BEGIN:initComponents

jButton1 = new javax.swing.JButton();
jPanel1 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
fieldNameLabel = new javax.swing.JLabel();
jLabel5 = new javax.swing.JLabel();
jScrollPane1 = new javax.swing.JScrollPane();
formatTextArea = new javax.swing.JTextArea();
jPanel2 = new javax.swing.JPanel();
jLabel3 = new javax.swing.JLabel();
fieldComboBox = new javax.swing.JComboBox();
jLabel4 = new javax.swing.JLabel();
deliminatorComboBox = new javax.swing.JComboBox();
jPanel3 = new javax.swing.JPanel();
applyButton = new javax.swing.JButton();
deleteButton = new javax.swing.JButton();
clearButton = new javax.swing.JButton();
closeButton = new javax.swing.JButton();

jButton1.setText("jButton1");

setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
setTitle("Project Field Output format");
setResizable(false);
addWindowListener(new java.awt.event.WindowAdapter() {
public void windowClosing(java.awt.event.WindowEvent evt) {
formWindowClosing(evt);
}
});

jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 14));
jLabel1.setText("Setup format for Field :");
jPanel1.add(jLabel1);

fieldNameLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14));
fieldNameLabel.setText("DefAUlt");
jPanel1.add(fieldNameLabel);

jLabel5.setText("Format");

jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
public void mousePressed(java.awt.event.MouseEvent evt) {
jScrollPane1MousePressed(evt);
}
});

formatTextArea.setColumns(20);
formatTextArea.setRows(5);
formatTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
public void mousePressed(java.awt.event.MouseEvent evt) {
formatTextAreaMousePressed(evt);
}
public void mouseReleased(java.awt.event.MouseEvent evt) {
formatTextAreaMouseReleased(evt);
}
});
formatTextArea.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
public void propertyChange(java.beans.PropertyChangeEvent evt) {
formatTextAreaPropertyChange(evt);
}
});
jScrollPane1.setViewportView(formatTextArea);

jPanel2.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

jLabel3.setText("Project Fields");
jPanel2.add(jLabel3);

fieldComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FirstName", "LastName", "Organisation" }));
fieldComboBox.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
fieldComboBoxActionPerformed(evt);
}
});
jPanel2.add(fieldComboBox);

jLabel4.setText("Select Delimiter");
jPanel2.add(jLabel4);

deliminatorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "$", "#", "!", "@" }));
deliminatorComboBox.setPreferredSize(new java.awt.Dimension(70, 27));
deliminatorComboBox.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
deliminatorComboBoxActionPerformed(evt);
}
});
jPanel2.add(deliminatorComboBox);

applyButton.setText("Apply");
applyButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
applyButtonActionPerformed(evt);
}
});
jPanel3.add(applyButton);

deleteButton.setText("Delete");
deleteButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
deleteButtonActionPerformed(evt);
}
});
jPanel3.add(deleteButton);

clearButton.setText(" Clear ");
clearButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
clearButtonActionPerformed(evt);
}
});
jPanel3.add(clearButton);

closeButton.setText("Close");
closeButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
closeButtonActionPerformed(evt);
}
});
jPanel3.add(closeButton);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
.addComponent(jLabel5)
.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
.addContainerGap())
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap(16, Short.MAX_VALUE)
.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(33, 33, 33)
.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jLabel5)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(18, 18, 18)
.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(34, 34, 34))
);

pack();
}//GEN-END:initComponents

private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
    //jTextArea1.setSelectionStart(3);
    //formatTextArea.setSelectionStart(6);
    selectedFieldFormatData.setFormat(formatTextArea.getText());
    if (parent instanceof OutputFormat) {
        ((OutputFormat) parent).updateTable();
    }
}//GEN-LAST:event_applyButtonActionPerformed

private void jScrollPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MousePressed
}//GEN-LAST:event_jScrollPane1MousePressed

private void formatTextAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formatTextAreaMousePressed
// TODO add your handling code here:
}//GEN-LAST:event_formatTextAreaMousePressed

private void formatTextAreaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formatTextAreaMouseReleased

    int caretIndex = formatTextArea.getCaretPosition();
    setSelectedFormatText(caretIndex);
}//GEN-LAST:event_formatTextAreaMouseReleased

private void formatTextAreaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formatTextAreaPropertyChange
}//GEN-LAST:event_formatTextAreaPropertyChange

private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    dispose();
    ((OutputFormat) parent).setEnabled(true);
}//GEN-LAST:event_closeButtonActionPerformed

private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    String txt = formatTextArea.getText();
    int startIndex = formatTextArea.getSelectionStart();
    int endIndex = formatTextArea.getSelectionEnd();

    if (txt.charAt(startIndex) == '<' && txt.charAt(endIndex - 1) == '>') {
        formatTextArea.setText(txt.substring(0, startIndex).trim() + txt.substring(endIndex).trim());
    }

}//GEN-LAST:event_deleteButtonActionPerformed

private void fieldComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldComboBoxActionPerformed
    if (fieldComboBox.getSelectedIndex() > 0) {
        formatTextArea.setText(formatTextArea.getText() + "<" + fieldComboBox.getSelectedItem().toString() + ">");
    }
}//GEN-LAST:event_fieldComboBoxActionPerformed

private void deliminatorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliminatorComboBoxActionPerformed
    formatTextArea.setText(formatTextArea.getText() + "<" + deliminatorComboBox.getSelectedItem().toString() + ">");
}//GEN-LAST:event_deliminatorComboBoxActionPerformed

private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
    formatTextArea.setText("");
}//GEN-LAST:event_clearButtonActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    dispose();
    ((OutputFormat) parent).setEnabled(true);
}//GEN-LAST:event_formWindowClosing

    public void setSelectedFormatText(int caretIndex) {
        String s = formatTextArea.getText();
        if (caretIndex > formatTextArea.getText().length() - 1) {
            return;
        }
        //System.out.println(s.charAt(jTextArea1.getSelectionStart()) + " : " + s.charAt(jTextArea1.getSelectionEnd()+1));
        if ((s.charAt(formatTextArea.getSelectionStart()) == '<') && (formatTextArea.getSelectionEnd() < (s.length())) && (s.charAt(formatTextArea.getSelectionEnd()) == '>')) {
            return;
        }

        int startIndex = s.charAt(caretIndex) != '<' ? s.substring(0, caretIndex).lastIndexOf('<') : caretIndex;
        int endIndex = s.charAt(startIndex) != '>' ? s.indexOf('>', caretIndex) : caretIndex;

        formatTextArea.setSelectionStart(startIndex);
        formatTextArea.setSelectionEnd(endIndex + 1);

    }
// Variables declaration - do not modify//GEN-BEGIN:variables
private javax.swing.JButton applyButton;
private javax.swing.JButton clearButton;
private javax.swing.JButton closeButton;
private javax.swing.JButton deleteButton;
private javax.swing.JComboBox deliminatorComboBox;
private javax.swing.JComboBox fieldComboBox;
private javax.swing.JLabel fieldNameLabel;
private javax.swing.JTextArea formatTextArea;
private javax.swing.JButton jButton1;
private javax.swing.JLabel jLabel1;
private javax.swing.JLabel jLabel3;
private javax.swing.JLabel jLabel4;
private javax.swing.JLabel jLabel5;
private javax.swing.JPanel jPanel1;
private javax.swing.JPanel jPanel2;
private javax.swing.JPanel jPanel3;
private javax.swing.JScrollPane jScrollPane1;
// End of variables declaration//GEN-END:variables
}
