/*
 * MailDialog.java
 *
 * Created on August 6, 2004, 3:54 PM
 */
package ui;

import client.Global;

import javax.swing.JOptionPane;

/**
 * This dialog is a container for the <code>ui.MailPanel</code>.
 * @author  Nancy McCall
 * @see ui.MailPanel
 */
public class MailDialog extends javax.swing.JDialog {
    
    public static MailDialog mail = null;
    public static MailPanel mailPanel = null;
    
    /** Creates new form MailDialog */
    public MailDialog() {
        super(JOptionPane.getFrameForComponent(Global.mainWindow));
        setModal(true);
        initComponents();
        getContentPane().add(MailPanel.getInstance());
        pack();
    }

    public static MailDialog getInstance() {
        if (mail == null) {
            mail = new MailDialog();
        }
        return mail;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setTitle("SPiCA Mail");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new MailDialog().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
