/*
 * QAgroupassignpage.java
 *
 * Created on August 19, 2008, 4:33 PM
 */

package ui;

import client.TaskExecuteQuery;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import model.QAGroupModel;

/**
 *
 * @author  Prakasha
 */
public class QAGroupAssignPage extends javax.swing.JFrame {
    
    /** Creates new form QAgroupassignpage */
    private Map qaGroupResult = null;
    private String projectName = null;
    private QAGroupModel qamodel = null;
    private String codersValue = null;
    private String fieldValues = null;
    private String volumeName = null;
    private int volumeId = 0;
    private JFrame parent;
    
    public QAGroupAssignPage() {
        initComponents();
    }
    
    public QAGroupAssignPage(Map qaGroupResult, String projectName,int volumeId, String coderValue,String fieldValue, JFrame parent) {
        this.qaGroupResult = qaGroupResult;
        this.projectName = projectName;
        this.codersValue = coderValue;
        this.fieldValues = fieldValue;
        this.volumeId = volumeId;
        this.parent = parent;
        setVolumeName();
    }

    private void setVolumeName() {   
             
             final TaskExecuteQuery task = new TaskExecuteQuery("qa.getVolumeName",Integer.toString(volumeId));
             task.setCallback((new Runnable() {
                    public void run() {
                try {
                    ResultSet results = (ResultSet) task.getResult();
                    while (results.next()) {                        
                        volumeName = results.getString(1);
                    }
                    initComponents();
                    fillProjectDetails();
                    fillQAGroupTable();
                } catch (SQLException ex) {
                    Logger.getLogger(QAGroupAssignPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }}));
            task.enqueue(this);
    }
    
    private void fillQAGroupTable() {
        if(null != qaGroupResult) {
            String headings[] = {"Group Number", "QA Level", "User Name", "Status"};
            Object object[][] = new Object[qaGroupResult.size() - 1][headings.length + 1];
            Set keySet = qaGroupResult.keySet();
            Iterator it = keySet.iterator();
            int i = 0;
            while(it.hasNext()) {
                Object nextValue = it.next();
                if(qaGroupResult.get(nextValue).getClass().getSimpleName().equals("ArrayList")) {
                    List valueList = (List)qaGroupResult.get(nextValue);
                    object[i][0] = valueList.get(0);
                    object[i][1] = valueList.get(1);
                    object[i][2] = valueList.get(2);
                    object[i][3] = valueList.get(3);
                    i++; 
                }
            }

             qamodel = new QAGroupModel(object , headings);
             qaGroupTable.setModel(qamodel);    
            }  
    }
    
    private void fillProjectDetails() {
        projectNameValueLabel.setText(projectName);
        volumeNameValueLabel.setText(volumeName);
        fieldNameValueLabel.setText(fieldValues);
        coderNameValueLabel.setText(codersValue);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qaHeaderLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qaGroupTable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        projectNameLabel = new javax.swing.JLabel();
        projectNameValueLabel = new javax.swing.JLabel();
        volumeNameLabel = new javax.swing.JLabel();
        fieldNameLabel = new javax.swing.JLabel();
        fieldNameValueLabel = new javax.swing.JLabel();
        volumeNameValueLabel = new javax.swing.JLabel();
        coderNameLabel = new javax.swing.JLabel();
        coderNameValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QA PROOFREADING");
        setResizable(false);

        qaHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        qaHeaderLabel.setText("QA PROOFREADING");

        qaGroupTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Group Number", "QA Level", "User Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(qaGroupTable);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(469, 92));
        jPanel1.setPreferredSize(new java.awt.Dimension(469, 92));

        projectNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        projectNameLabel.setText("Project :");

        projectNameValueLabel.setMaximumSize(new java.awt.Dimension(150, 10));
        projectNameValueLabel.setPreferredSize(new java.awt.Dimension(150, 10));

        volumeNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        volumeNameLabel.setText("Volume :");

        fieldNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        fieldNameLabel.setText("Field Names :");

        fieldNameValueLabel.setMaximumSize(new java.awt.Dimension(400, 10));
        fieldNameValueLabel.setPreferredSize(new java.awt.Dimension(400, 10));
        fieldNameValueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fieldNameValueLabelMouseEntered(evt);
            }
        });
        fieldNameValueLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNameValueLabelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNameValueLabelFocusLost(evt);
            }
        });

        volumeNameValueLabel.setMaximumSize(new java.awt.Dimension(150, 10));
        volumeNameValueLabel.setPreferredSize(new java.awt.Dimension(150, 10));

        coderNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        coderNameLabel.setText("Coder Names :");

        coderNameValueLabel.setMaximumSize(new java.awt.Dimension(400, 10));
        coderNameValueLabel.setPreferredSize(new java.awt.Dimension(400, 10));
        coderNameValueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coderNameValueLabelMouseEntered(evt);
            }
        });
        coderNameValueLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                coderNameValueLabelFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectNameLabel)
                    .addComponent(coderNameLabel)
                    .addComponent(fieldNameLabel))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(coderNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(projectNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(volumeNameLabel)
                            .addGap(36, 36, 36)
                            .addComponent(volumeNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(85, 85, 85))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(fieldNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel)
                    .addComponent(volumeNameLabel)
                    .addComponent(volumeNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNameLabel)
                    .addComponent(fieldNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coderNameLabel)
                    .addComponent(coderNameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(closeButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(qaHeaderLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(qaHeaderLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameValueLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNameValueLabelFocusGained
        fieldNameValueLabel.setToolTipText(fieldValues);
    }//GEN-LAST:event_fieldNameValueLabelFocusGained

    private void fieldNameValueLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNameValueLabelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameValueLabelFocusLost

    private void coderNameValueLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coderNameValueLabelFocusGained
        coderNameValueLabel.setToolTipText(codersValue);
    }//GEN-LAST:event_coderNameValueLabelFocusGained

    private void fieldNameValueLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldNameValueLabelMouseEntered
        fieldNameValueLabel.setToolTipText(fieldValues);
    }//GEN-LAST:event_fieldNameValueLabelMouseEntered

    private void coderNameValueLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coderNameValueLabelMouseEntered
        coderNameValueLabel.setToolTipText(codersValue);
    }//GEN-LAST:event_coderNameValueLabelMouseEntered
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QAGroupAssignPage().setVisible(true);
            }
        });
    }
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        setVisible(false);
        dispose();
        this.parent.setVisible(true);
    }  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel coderNameLabel;
    private javax.swing.JLabel coderNameValueLabel;
    private javax.swing.JLabel fieldNameLabel;
    private javax.swing.JLabel fieldNameValueLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JLabel projectNameValueLabel;
    private javax.swing.JTable qaGroupTable;
    private javax.swing.JLabel qaHeaderLabel;
    private javax.swing.JLabel volumeNameLabel;
    private javax.swing.JLabel volumeNameValueLabel;
    // End of variables declaration//GEN-END:variables
    
}

