/*
 * TextSearchWindow.java
 *
 * Created on March 25, 2008, 11:17 AM
 */
package ui;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import model.SQLManagedComboModel;

/**
 * Dialog to Search Text in Exported Project FieldValues
 *
 * @author  yuvaraj
 */
public class TextSearchWindow extends javax.swing.JDialog
{

   private final String GET_ALL_PROJECTS = "AdvanceValidation.projectCombo";
   private final String GET_ALL_FIELDS = "TextSearch.fieldCombo";
   private SQLManagedComboModel projectModel = null;
   private int projectId = 0;
   private String word = null;
   private String fileName = null;
   private String line = null;
   private int seq = 1;
   private StringBuffer linesLoc = null;
   private List list = null;
   private BufferedReader in;
   private JDialog parent;
   private String fieldDelimiter = null;
   private String textQualifier = null;

   /** Creates new form TextSearchWindow */
   public TextSearchWindow(JDialog parent, String file, String text)
   {
      super(parent);
      word = text;
      fileName = file;
      this.parent = parent;
      initComponents();

      projectModel = new SQLManagedComboModel(GET_ALL_PROJECTS);
      projectModel.register();
      jComboBox2.setModel(projectModel);
   }
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jComboBox1 = new javax.swing.JComboBox();
      jComboBox2 = new javax.swing.JComboBox();
      jComboBox3 = new javax.swing.JComboBox();
      jComboBox4 = new javax.swing.JComboBox();
      jLabel6 = new javax.swing.JLabel();
      jTextField1 = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      jTextField2 = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("TEXT SEARCH");

      jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

      jLabel2.setFont(new java.awt.Font("Dialog", 1, 12));
      jLabel2.setForeground(new java.awt.Color(0, 51, 153));
      jLabel2.setText("TREATMENT :");

      jLabel3.setFont(new java.awt.Font("Dialog", 1, 12));
      jLabel3.setForeground(new java.awt.Color(0, 51, 153));
      jLabel3.setText("PROJECT NAME :");

      jLabel4.setFont(new java.awt.Font("Dialog", 1, 12));
      jLabel4.setForeground(new java.awt.Color(0, 51, 153));
      jLabel4.setText("FILE TYPE :");

      jLabel5.setFont(new java.awt.Font("Dialog", 1, 12));
      jLabel5.setForeground(new java.awt.Color(0, 51, 153));
      jLabel5.setText("FIELD TO SEARCH :");

      jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GM", "NON-GM" }));
      jComboBox1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
         }
      });

      jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      jComboBox2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox2ActionPerformed(evt);
         }
      });

      jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".TXT", ".LFP", ".LOG" }));
      jComboBox3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox3ActionPerformed(evt);
         }
      });

      jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      jComboBox4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox4ActionPerformed(evt);
         }
      });

      jLabel6.setFont(new java.awt.Font("Dialog", 1, 12));
      jLabel6.setForeground(new java.awt.Color(0, 51, 153));
      jLabel6.setText("FIELD DELIMITER :");

      jLabel7.setFont(new java.awt.Font("Dialog", 1, 12));
      jLabel7.setForeground(new java.awt.Color(0, 51, 153));
      jLabel7.setText("TEXT QUALIFIER :");

      jTextField2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField2ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2)
               .addComponent(jLabel3)
               .addComponent(jLabel4)
               .addComponent(jLabel5)
               .addComponent(jLabel6))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jComboBox1, 0, 118, Short.MAX_VALUE))
                  .addContainerGap())
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(20, 20, 20)
                  .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(jLabel7)
                  .addGap(18, 18, 18)
                  .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addContainerGap())))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(19, 19, 19)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(17, 17, 17)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(32, 32, 32)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel7)
               .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(39, Short.MAX_VALUE))
      );

      jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
      jLabel1.setForeground(new java.awt.Color(0, 51, 204));
      jLabel1.setText("TEXT SEARCH");

      jButton1.setText("PROCESS");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setText("CLOSE");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(114, 114, 114)
                  .addComponent(jButton1)
                  .addGap(54, 54, 54)
                  .addComponent(jButton2))
               .addGroup(layout.createSequentialGroup()
                  .addGap(143, 143, 143)
                  .addComponent(jLabel1))
               .addGroup(layout.createSequentialGroup()
                  .addGap(49, 49, 49)
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(62, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton1)
               .addComponent(jButton2))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      setVisible(false);
      parent.setVisible(true);
   //System.exit(0);
   }//GEN-LAST:event_jButton2ActionPerformed

   private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      if (jComboBox2.getSelectedIndex() > -1) {
         int sel = jComboBox2.getSelectedIndex();
         projectId = ((SQLManagedComboModel) jComboBox2.getModel()).getIdAt(sel);
         projectModel = new SQLManagedComboModel(GET_ALL_FIELDS, projectId);
         projectModel.register();
         jComboBox4.setModel(projectModel);
      }
      
   }//GEN-LAST:event_jComboBox2ActionPerformed

   private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
     
   }//GEN-LAST:event_jComboBox3ActionPerformed

   private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
      
   }//GEN-LAST:event_jComboBox4ActionPerformed

   private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   // TODO add your handling code here:
   }//GEN-LAST:event_jComboBox1ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if (jComboBox2.getSelectedIndex() < 0) {
         JOptionPane.showMessageDialog(this, "Select any project name");
         jComboBox2.requestFocus();
      }
      else if (jComboBox4.getSelectedIndex() < 0) {
         JOptionPane.showMessageDialog(this, "Select any field name");
         jComboBox4.requestFocus();
      }
      else if (jTextField1.getText().trim().length() == 0) {
         JOptionPane.showMessageDialog(this, "Please specify a field delimiter");
         jTextField1.requestFocus();
      }
      else if (jTextField2.getText().trim().length() == 0) {
         JOptionPane.showMessageDialog(this, "Please specify a text qualifier");
         jTextField2.requestFocus();
      }
      else if (jTextField1.getText().trim().length() > 1) {
         JOptionPane.showMessageDialog(this, "Please specify only a single field delimiter");
         jTextField1.requestFocus();
      }
      else if (jTextField2.getText().trim().length() > 1) {
         JOptionPane.showMessageDialog(this, "Please specify only a single text qualifier");
         jTextField2.requestFocus();
      }
      else {         
         list = new ArrayList();
         fieldDelimiter = jTextField1.getText();
         textQualifier = jTextField2.getText();
         seq = ((SQLManagedComboModel) jComboBox4.getModel()).getIdAt(jComboBox4.getSelectedIndex());

         try {
            BufferedReader in = new BufferedReader(new FileReader(fileName));
            while ((line = in.readLine()) != null) {
               process_line(line, fieldDelimiter, textQualifier, seq);
            }

            if (list != null && list.size() != 0) {
               setVisible(false);
               TSearchReportFrame report = new TSearchReportFrame(this, word, list, jComboBox4.getSelectedItem().toString());
               report.setLocationRelativeTo(null);
               report.setVisible(true);
            }
            else {
               JOptionPane.showMessageDialog(this, "Text not found in the file");
            }
         } catch (Exception e) {
            e.printStackTrace();
         }

      }
   }//GEN-LAST:event_jButton1ActionPerformed

   private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
   // TODO add your handling code here:
   }//GEN-LAST:event_jTextField2ActionPerformed

   private void process_line(String line, String fieldDelimiter, String textQualifier, int seq)
   {
      linesLoc = new StringBuffer();
      int i = 1;
      String batesNum = null;
      String value = null;
      if ((line).indexOf(word) >= 0) {
         StringTokenizer tok = new StringTokenizer(line, fieldDelimiter);
         while (tok.hasMoreTokens()) {
            String str = tok.nextToken().trim();
            linesLoc.append(str);
         }
         StringTokenizer tokStr = new StringTokenizer(linesLoc.toString(), textQualifier);
         while (tokStr.hasMoreTokens()) {
            if (i == 1) {
               batesNum = tokStr.nextToken().trim();
            }
            else {
               value = tokStr.nextToken().trim();
            }
            if (i == 4 + seq && value.contains(word)) {
               list.add(batesNum + ":" + value);
            }
            i++;
         }
      }
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JComboBox jComboBox1;
   private javax.swing.JComboBox jComboBox2;
   private javax.swing.JComboBox jComboBox3;
   private javax.swing.JComboBox jComboBox4;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   // End of variables declaration//GEN-END:variables

}
